### PR TITLE
Update docs

### PR DESCRIPTION
**Pull request by pasuder**

### CODE REVIEW

**Comment by pasuder** [comment]
@dice-cyfronet/atmo-dev-team what would you like to see more in [`README.md`](https://github.com/dice-cyfronet/ip-wrangler/blob/task_update_docs/README.md)?

**Comment by mkasztelnik** [comment]
Aha, here you can add general introduction :smile:

**Comment by pasuder** [comment]
Amazing :smile: Check: https://www.google.pl/search?q=portostawiaczka

**Comment by pasuder** [comment]
What about current description?

**Comment by mkasztelnik** [comment]
Much more better. I propose to not mention about Atmosphere like the only app which can use it. It is generic purpose tool and it should be highlighted in `README.md`.

When everything will be ready please ask @nowakowski to do proofreading

**Comment by pasuder** [comment]
Should I write information about integrating `logrotate` to rolling logs?

**Comment by mkasztelnik** [comment]
IMHO no. Information about log rotate are easily googlable.

**Comment by pasuder** [comment]
I added information about `log'n'roll` in 7c1c44b2 as @tbartynski mentions in #12.

**Comment by mkasztelnik** [comment]
:+1:

**Comment by pasuder** [comment]
@nowakowski could you perform the proofreading process?

**Comment by nowakowski** [comment]
Oh bummer... I proofread master. Sorry. :/

**Comment by nowakowski** [comment]
Okay, reverted master by 1 commit and pushed changes to task_update_docs. Hope I didn't mess up too badly. :)

**Comment by nowakowski** [comment]
:+1:

**Comment by pasuder** [comment]
I would like to say :+1: for @nowakowski changes :smiley:

**Pull request merged**
