### PR TITLE
Don't remove log

### PR DESCRIPTION
**Pull request by pasuder**
Due to #11

### CODE REVIEW

**Comment by mkasztelnik** [comment]
:+1:

**Comment by pasuder** [comment]
@tbartynski would like not to lose logs from `ip-wrangler` if the app is restarted? Please review this changes.

**Comment by tbartynski** [comment]
I believe that appending and rolling logs is the way to go. If rolling is configured I give :+1:

**Comment by mkasztelnik** [comment]
Rolling can be configured using e.g. logrotate and it is up to `ip-wrangler` user to configure it. Info how it can be made can be added in the scope of #10.

**Comment by pasuder** [comment]
Ruby `Logger` provide mechanism for rolling logs (see [this](http://www.ruby-doc.org/stdlib-2.2.0/libdoc/logger/rdoc/Logger.html#class-Logger-label-How+to+create+a+logger)), but not every logs are gathered by `Logger`. Some of them (like `stdout` from `thin`) are written to file directly.

**Comment by pasuder** [comment]
@tbartynski I added information about `log'n'roll` in updated [`README.md`](https://github.com/dice-cyfronet/ip-wrangler/blob/task_update_docs/README.md#lognroll). Does it fit you?

**Comment by tbartynski** [comment]
Yup. I like it.

:+1:

**Pull request merged**
